initial commit

diff --git a/services/wslda-vortex-analysis/.dev-ubuntu-24.10/.config/usr/local/bin/entrypoint b/services/wslda-vortex-analysis/.dev-ubuntu-24.10/.config/usr/local/bin/entrypoint
--- a/services/wslda-vortex-analysis/.dev-ubuntu-24.10/.config/usr/local/bin/entrypoint
+++ b/services/wslda-vortex-analysis/.dev-ubuntu-24.10/.config/usr/local/bin/entrypoint
@@ -54,14 +54,8 @@ while [ $# -gt 0 ]; do
             ;;
 
         # case:
-        "--app-analysis-results-data-dir")
-            APP_ANALYSIS_RESULTS_DATA_DIR="$2"
-            shift 2
-            ;;
-
-        # case:
-        "--app-analysis-results-analysis-dir")
-            APP_ANALYSIS_RESULTS_ANALYSIS_DIR="$2"
+        "--app-analysis-resultsdir")
+            APP_ANALYSIS_RESULTSDIR="$2"
             shift 2
             ;;
 
@@ -82,11 +76,10 @@ HEADER+="# >>> entrypoint:\n"
 HEADER+="# >>> - args:\n"
 HEADER+="# >>> ---- . ---- ---- ---- ---- . ----\n"
 HEADER+="\n"
-HEADER+="APP_ANALYSIS_WORKDIR: ................ ${APP_ANALYSIS_WORKDIR}\n"
-HEADER+="APP_ANALYSIS_CONFIGDIR: .............. ${APP_ANALYSIS_CONFIGDIR}\n"
-HEADER+="APP_ANALYSIS_TEMPLATEDIR: ............ ${APP_ANALYSIS_TEMPLATEDIR}\n"
-HEADER+="APP_ANALYSIS_RESULTS_DATA_DIR: ....... ${APP_ANALYSIS_RESULTS_DATA_DIR}\n"
-HEADER+="APP_ANALYSIS_RESULTS_ANALYSIS_DIR: ... ${APP_ANALYSIS_RESULTS_ANALYSIS_DIR}"
+HEADER+="APP_ANALYSIS_WORKDIR: ....... ${APP_ANALYSIS_WORKDIR}\n"
+HEADER+="APP_ANALYSIS_CONFIGDIR: ..... ${APP_ANALYSIS_CONFIGDIR}\n"
+HEADER+="APP_ANALYSIS_TEMPLATEDIR: ... ${APP_ANALYSIS_TEMPLATEDIR}\n"
+HEADER+="APP_ANALYSIS_RESULTSDIR: .... ${APP_ANALYSIS_RESULTSDIR}\n"
 HEADER+="\n"
 echo -e "${HEADER}"
 
@@ -99,11 +92,11 @@ if [[ ! -d "${APP_ANALYSIS_CONFIGDIR}" ]]; then echo ">>> ERROR: '${APP_ANALYSIS
 # $APP_ANALYSIS_TEMPLATEDIR directory must exist:
 if [[ ! -d "${APP_ANALYSIS_TEMPLATEDIR}" ]]; then echo ">>> ERROR: '${APP_ANALYSIS_TEMPLATEDIR}' directory does not exist" && exit 1; fi
 
-# $APP_ANALYSIS_RESULTS_DATA_DIR directory must exist:
-if [[ ! -d "${APP_ANALYSIS_RESULTS_DATA_DIR}" ]]; then echo ">>> ERROR: '${APP_ANALYSIS_RESULTS_DATA_DIR}' directory does not exist" && exit 1; fi
+# $APP_ANALYSIS_RESULTSDIR directory must exist:
+if [[ ! -d "${APP_ANALYSIS_RESULTSDIR}" ]]; then echo ">>> ERROR: '${APP_ANALYSIS_RESULTSDIR}' directory does not exist" && exit 1; fi
 
-# $APP_ANALYSIS_RESULTS_ANALYSIS_DIR directory must exist:
-if [[ ! -d "${APP_ANALYSIS_RESULTS_ANALYSIS_DIR}" ]]; then echo ">>> ERROR: '${APP_ANALYSIS_RESULTS_ANALYSIS_DIR}' directory does not exist" && exit 1; fi
+# $APP_ANALYSIS_RESULTSDIR directory must exist:
+if [[ ! -d "${APP_ANALYSIS_RESULTSDIR}" ]]; then echo ">>> ERROR: '${APP_ANALYSIS_RESULTSDIR}' directory does not exist" && exit 1; fi
 
 #? ---- . ---- ---- ---- ---- . ----
 #? envs:
